src/Entity/ImageField.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Image
 * @ORM\HasLifecycleCallbacks
 */
abstract class ImageField
{
    private $temp;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */

    /**
     * @ORM\Column(type="string", length=255, )
     */
    public $path;

    /**
     * @Assert\File(maxSize="6000000")
     */
    private $file;

    private $wide_dimensions;

    private $filenames;

    public function getWideDimensions(){
        $this->loadData();
        return $this->wide_dimensions;
    }

    public function getConstraintWideDimensions(){
        $this->loadData();
        $dimensions = array();
        foreach ($this->wide_dimensions as $dimension)
            if ($this->getOriginalImageWidth() >= $dimension)
                array_push($dimensions, $dimension);

        return $dimensions;
    }

    public function loadData()
    {
        /*This array need to be sortes ascendent*/
        $this->wide_dimensions = [20, 500, 800, 1200, 1900, 3600];
        $this->filenames = [];
        foreach ($this->wide_dimensions as $wide)
            array_push($this->filenames, $this->getAbsolutePath().'-'.$wide.'.jpg');
    }


    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
        // check if we have an old image path
        if (isset($this->path)) {
            // store the old name to delete after the update
            $this->temp = $this->path;
            $this->path = null;
        } else {
            $this->path = 'initial';
        }

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }

    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir().'/'.$this->path;
    }

    public function getWebPath($size = 500)
    {

        $prefixPath = 'uploads/images/';
        $path = $prefixPath.$this->getUploadDir().'/'.$this->path;

        if ($size == null)
            return $path;

        $this->loadData();

        if ($size == null)
            return $path;

        for ($i = 0; count($this->wide_dimensions); $i++)
            if($this->wide_dimensions[$i]==$size)
                return $path.'-'.$size.'.jpg';

    }

    public function getFullImageWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir().'/'.$this->path;
    }

    public function getOriginalImageWidth(){
        $data = getimagesize($this->getAbsolutePath());
        $width = $data[0];
        return $width;
    }

    protected function getUploadRootDir()
    {
        // la ruta absoluta del directorio donde se deben
        // guardar los archivos cargados
        return  __DIR__ . '/../../public/uploads/images/' .$this->getUploadDir();
    }

    abstract function getUploadDir();

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->getFile()) {
            return;
        }

        // si hay un error al mover el archivo, move() automáticamente
        // envía una excepción. This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move($this->getUploadRootDir(), $this->path);
        $this->createThumb();

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            @unlink($this->getUploadRootDir().'/'.$this->temp);
            // clear the temp image path
            $this->temp = null;
        }
        $this->file = null;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null !== $this->getFile()) {
            // haz lo que quieras para generar un nombre único
            $filename = substr(sha1(uniqid(mt_rand(), true)),0,10);
            $this->path = $filename.'.'.$this->getFile()->guessExtension();
        }
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if ($file = $this->getAbsolutePath()) {
            @unlink($file);
            $this->removeThumbs();
        }
    }

    /**
     * Set path
     *
     * @param string $path
     *
     * @return Imagen
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    private function createThumb()
    {
        $this->loadData();
        $image = null;
        if(strpos($this->getAbsolutePath(),".png"))
            $image = @imagecreatefrompng($this->getAbsolutePath());
        else
            $image = @imagecreatefromjpeg($this->getAbsolutePath());

        $width = imagesx($image);
        $height = imagesy($image);
        $original_aspect = $height / $width;
        for($i = 0; $i<count($this->wide_dimensions); $i++)
        {
            $thumb_width = $this->wide_dimensions[$i];

            if ($width < $thumb_width)
                continue;

            $thumb_height = $original_aspect*$thumb_width;

            $thumb = imagecreatetruecolor( $thumb_width, $thumb_height );

            imagecopyresampled($thumb,
                $image,
                0, 0,
                0, 0,
                $thumb_width, $thumb_height,
                $width, $height);

            imageinterlace($thumb, true);
            @imagejpeg($thumb, $this->filenames[$i], 85);

        }
    }

    public function removeThumbs()
    {
        $this->loadData();
        if($file = $this->getAbsolutePath())
        {
            foreach ($this->filenames as $filename)
                @unlink($filename);
        }
    }

    public function updateThumbs(){
        $this->removeThumbs();
        $this->createThumb();
    }
}

templates/modules/footer.html.twig
<footer class="footer">

    <div class="wrapper">
        <div class="row row--gutters">
            <div class="row__medium-2">
                <div class="footer__logo footer--subsection footer--subsection--m-t">
                    <img class="lazyload" data-src="{{ asset('assets/images/icons/logo_footer.svg') }}" alt="">
                </div>
            </div>

            <div class="row__medium-5">
                <div class="footer__subscription footer--subsection">
                    <p>Suscríbete a nuestra lista de correos y te enviaremos
                        noticias, concursos y convocatorias abiertas
                        relacionadas con el mundo del cartel.
                    </p>

                    <form class="footer__subscription__form" action="http://cartelon.test/index.php/mail" method="POST">
                        <input class="footer__subscription__form__item footer__subscription__form__item__email" type="email" placeholder="Su correo" required>
                        <input class="footer__subscription__form__item footer__subscription__form__item__submit" type="submit" value="Suscribirse">
                    </form>

                    <p class="footer__subscription__message"></p>


                </div>
            </div>

            <div class="row__medium-5">
                <div class="footer__contact footer--subsection">
                    <address>
                        <dl>
                            {% if projectInfo and projectInfo.address %}
                            <dt class="footer__contact__item">
                                <img class="lazyload" data-src="{{ asset('assets/images/icons/marker.svg') }}" alt="">
                                <p>Direccion: {{ projectInfo.address }}</p>
                            </dt>
                            {% endif %}
                            {% if projectInfo and projectInfo.email %}
                            <dt class="footer__contact__item">
                                <p>
                                    ¿Interesado en nuestras producciones?
                                    <br/>
                                    Contáctenos:
                                    <br/>
                                    <img class="lazyload" data-src="{{ asset('assets/images/icons/message.svg') }}" alt="mail-icon">
                                    &nbsp;
                                    <a href="mailto:{{ projectInfo.email }}">
                                        {{ projectInfo.email }}
                                    </a>
                                </p>
                            </dt>
                            {% endif %}
                            {% if projectInfo and projectInfo.phone %}
                            <dt class="footer__contact__item">
                                <img class="lazyload" data-src="{{ asset('assets/images/icons/phone.svg') }}" alt="">
                                <p>Telefono: {{ projectInfo.phone }}</p>
                            </dt>
                            {% endif %}
                            <dt>
                                <div class="footer__social-networks footer--subsection">
                                    <ul>
                                        <li><a href="https://www.facebook.com/cartelon.cuba/">
                                                <img class="lazyload" data-src="{{ asset('assets/images/icons/facebook.svg') }}" alt="">
                                            </a></li>
                                        <li><a href="https://www.instagram.com/cartelon.cuba/">
                                                <img class="lazyload" data-src="{{ asset('assets/images/icons/instagram.svg') }}" alt="">
                                            </a></li>
                                        {#
                                        <li><a href="#">
                                                <img class="lazyload" data-src="{{ asset('assets/images/icons/twitter.svg') }}" alt="">
                                            </a>
                                        </li>
                                        #}
                                    </ul>
                                </div>
                            </dt>
                        </dl>
                    </address>
                </div>
            </div>
        </div>

        <div class="footer__copyright">
            <p>{{ date | date('Y') }} Copyright CartelON Cuba.</p>
        </div>
    </div>

    <div class="footer__authors">
        <p>
            Desing by <a href="http://guillomoreno.com/">guillomoreno</a>
            and code by <a href="http://habana.tech">habana.tech</a>
        </p>
    </div>

</footer>

templates/modules/header.html.twig
<header class="header">
    <div class="wrapper">
        <div class="header__logo">
            <a href="#start">
                <img src="{{ asset('assets/images/icons/logo_header.svg') }}" alt="logo">
            </a>
        </div>

        <div class="header__menu-icon">
            <div class="header__menu-icon__middle"></div>
        </div>

        <div class="header__menu-content">
            <nav class="nav nav--pull-right">
                <ul>
                    <li id="start-link">
                        <a href="#start">Inicio</a>
                    </li>

                    <li id="us-link">
                        <a href="#us">Nosotros</a>
                    </li>

                    <li id="news-link">
                        <a href="#news">Noticias</a>
                    </li>

                    <li id="posters-link">
                        <a href="#posters">Carteles</a>
                    </li>

                    <li id="events-link">
                        <a href="#events">Eventos</a>
                    </li>

                    <li id="videos-link">
                        <a href="#videos">Video Galer&iacute;a</a>
                    </li>
                </ul>
            </nav>
        </div>

    </div>
</header>

templates/modules/poster-big.html.twig
<div class="poster-big">
    <div class="poster-big__close btn__close"></div>
    <div class="poster-big__prev btn__prev"></div>
    <div class="poster-big__next btn__next"></div>
    <div class="wrapper">
        <div class="poster-big__overflow-scroll-y">
            <div class="row row--gutters poster-big__content">
                <div class="row__medium-2 poster-big__details">
                    <div class="poster-big__details__items">
                        <a href="#" class="poster-big__details__items__link__0" data-img="" data-img-max-width="">
                            <img class="poster-big__details__item__image__0">
                        </a>
                        <a href="#" class="poster-big__details__items__link__1" data-img="" data-img-max-width="">
                            <img class="poster-big__details__item__image__1">
                        </a>
                        <a href="#" class="poster-big__details__items__link__2" data-img="" data-img-max-width="">
                            <img class="poster-big__details__item__image__2">
                        </a>

                    </div>
                </div>
                <div class="row__medium-5 poster-big__content__image">
                    <img class="poster-big__image" alt="">
                </div>
                <div class="row__medium-5 poster-big__content__description">
                    <div class="poster-big__description">
                        <h3 class="poster-big__description__title">Poster Title / Year</h3>
                        <h4 class="poster-big__description__subtitle">Poster Subtitle</h4>
                        <div class="poster-big__description__overflow-scroll-y">
                            <p class="poster-big__description__text">Lorem ipsum dolor sit amet
                                consectetur adipisicing elit. Non nemo architecto dicta
                                illum illo? Quis voluptatibus?</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/modules/section__events.html.twig
<section class="section" id="events" data-nav-link="#events-link" data-nav-link-prev="#posters-link">
    <div class="wrapper wrapper-medium">
        <h2 class="section__title">Eventos</h2>

        {% set eventFirst = events | first %}
        <div id="event_0" class="info-block">
            <div class="info-block__image">
                <img
                        class="lazyload blur-up"
                        decoding="async"
                        sizes="(max-width: 760px) 50vw, 90vw"
                        src="{{ asset(eventFirst.webPath(20)) }}"
                        data-srcset="
                    {% for dimension in eventFirst.getConstraintWideDimensions %}
                        {% if not loop.last %}
                            {{ asset(eventFirst.webPath(dimension)) }} {{ dimension }}w,
                        {% else %}
                            {{ asset(eventFirst.webPath(dimension)) }} {{ dimension }}w
                        {% endif %}
                    {% endfor %}
                " alt="{{ eventFirst.name }}">
            </div>

            <div class="info-block__description
                    info-block__description--float">
                <h3 class="info-block__description__title">{{ eventFirst.name }}</h3>
                <h4 class="info-block__description__subtitle">
                    {{ eventFirst.datetime | localizeddate('full', 'short', 'es') }}
                    <br>
                    <strong>Lugar:</strong> {{ eventFirst.place }}
                </h4>
                <p class="info-block__description__text">
                    {{ eventFirst.description | slice (0, 250) | nl2br  }}...
                </p>
                <br/>
                <div class="event__button event__button--event-0 wrapper--center-text">
                    <a class="btn btn--blue" href="#event_expand_0" data-event-expand="#event_expand_0" data-event="#event_0">Ver más</a>
                </div>
            </div>
        </div>

        <div class="grid-event__expand">

            <div id="event_expand_0" class="event__expand">

                <div>
                    <div class="event__expand__close btn__close"></div>
                    <div class="event__expand__carousel">
                        {% for imageInGallery in eventFirst.imageGalleries %}
                            <div class="event__expand__carousel__cell">
                                <img
                                    class="event__expand__image lazyload blur-up"
                                    src="{{ asset(imageInGallery.getWebPath(20)) }}"
                                    sizes="(max-width: 799px) 90vw, 100vw"
                                    data-srcset="
                                {% for dimension in imageInGallery.getConstraintWideDimensions %}
                                    {% if not loop.last %}
                                        {{ asset(imageInGallery.webPath(dimension)) }} {{ dimension }}w,
                                    {% else %}
                                        {{ asset(imageInGallery.webPath(dimension)) }} {{ dimension }}w
                                    {% endif %}
                                {% endfor %}"
                                alt="{{ imageInGallery.description }}">
                            </div>
                        {% endfor %}

                    </div>

                    <div class="wrapper">
                        <h3 class="event__expand__title">{{ eventFirst.name }}</h3>
                        <h4 class="event__expand__subtitle">{{ eventFirst.datetime | localizeddate('full', 'short', 'es') }}, {{ eventFirst.place }}</h4>
                        <p class="event__expand__text">
                            {{ eventFirst.description | nl2br }}
                        </p>
                        <a data-collapse="true" href="#event_0">
                            <div class="btn__collapse">
                            </div>
                        </a>
                    </div>
                </div>
            </div>

        </div>

        <div id="events-container" class="section__container">
            {% for event in events | slice(1 , events | length) %}
                {% set index = loop.index %}
                {% if loop.index0 % 2 == 0%}
                    <div class="grid-event">
                {% endif %}

                <div id="event_{{ index }}" class="event
                                                    grid-event__{{ loop.index0 % 2 ==0 ? 'first' : 'second' }}
                                                    {{ (loop.last and (events | length % 2 ==0)) ? 'event--center' : ''}}">
                    <img
                        class="lazyload blur-up"
                        decoding="async"
                        sizes="(max-width: 760px) 50vw, 90vw"
                        src="{{ asset(event.webPath(20)) }}"
                        data-srcset="
                        {% for dimension in event.getConstraintWideDimensions %}
                            {% if not loop.last %}
                                {{ asset(event.webPath(dimension)) }} {{ dimension }}w,
                            {% else %}
                                {{ asset(event.webPath(dimension)) }} {{ dimension }}w
                            {% endif %}
                        {% endfor %}
                        " alt="{{ event.name }}">
                    <div class="event__description">
                        <h4 class="event__title">{{ event.name }}</h4>
                        <p class="event__description__text">
                            {{ event.datetime | localizeddate('full', 'short', 'es') }}
                            <br/>
                            <strong>Lugar: </strong> {{ event.place }}
                        </p>
                    </div>
                    <div class=" event__button wrapper--center-text">
                        <a class="btn" href="#event_expand_{{ index }}" data-event-expand="#event_expand_{{ index }}" data-event="#event_{{ index }}">Ver más</a>
                    </div>
                </div>

                <div class="grid-event__expand">

                    <div id="event_expand_{{ index }}" class="event__expand">

                        <div>
                            <div class="event__expand__close btn__close"></div>
                            <div class="event__expand__carousel" >
                                {% for imageInGallery in event.imageGalleries %}
                                    <div class="event__expand__carousel__cell">
                                        <img
                                            class="event__expand__image lazyload blur-up"
                                            src="{{ asset(imageInGallery.getWebPath(20)) }}"
                                            sizes="(max-width: 799px) 90vw, 100vw"
                                            data-srcset="
                                            {% for dimension in imageInGallery.getConstraintWideDimensions %}
                                                {% if not loop.last %}
                                                    {{ asset(imageInGallery.webPath(dimension)) }} {{ dimension }}w,
                                                {% else %}
                                                    {{ asset(imageInGallery.webPath(dimension)) }} {{ dimension }}w
                                                {% endif %}
                                            {% endfor %}"
                                            alt="{{ imageInGallery.description }}">
                                    </div>
                                {% endfor %}

                            </div>

                            <div class="wrapper">
                                <h3 class="event__expand__title">{{ event.name }}</h3>
                                <h4 class="event__expand__subtitle">{{ event.datetime | localizeddate('full', 'short', 'es') }}, {{ event.place }}</h4>
                                <p class="event__expand__text">
                                    {{ event.description | nl2br }}
                                </p>
                                <a data-collapse="true" href="#event_{{ index }}">
                                    <div class="btn__collapse">
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>

                </div>

                {% if loop.index0 % 2 == 1 or loop.last%}
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        {% if moreEvent %}
            <div id="events__load__wrapper" class="load__animation__wrapper">
                <div class="load__animation__wrapper__element"></div>
            </div>

            <div id="wrapper-loadMoreEvents" class="wrapper--center-text">
                <a href="#" id="loadMoreEvents" class="btn btn--blue-inverse">Ver más eventos</a>
            </div>
        {% endif %}
    </div>
</section>

templates/modules/section__posters.html.twig
<section class="section" id="posters" data-nav-link="#posters-link" data-nav-link-prev="#news-link">
    <div class="wrapper">
        <h2 class="section__title">Carteles</h2>

        <div class="wrapper wrapper--big">
            <p class="poster__text">
                {% if projectInfo and projectInfo.posterInfo %}
                    {{ projectInfo.posterInfo | raw | nl2br }}
                {% else %}
                    Impresión serigráfica, Cartulina 180gramos, Cuño seco, seriados y firmados, Formato 50x70cm,
                    Edición Limitada 50U.
                    <br/>
                    Printed on silkscreen, cardboard 180gr, dry stamp, serials and signed,
                    Format 19 ½ x 27 ½ “, Limited edition 50U.
                {% endif %}
            </p>
        </div>

        <div class="filter">
            <form class="filter__form">
                <label for="#filter" class="filter__text">Puedes buscar por autor, proyecto o año</label>
                <input class="filter__input" type="text" id="filter" placeholder="Diseñador, proyecto, año" required>
                <div class="filter__reset"></div>
                <input type="submit" class="filter__button btn btn--blue-inverse" value="Buscar">
            </form>
        </div>

        <div class="poster">

            <div class="poster__initial poster--visible  row row--gutters">
                {% set index = 0 %}
                {% for posterEvent in posterEvents %}

                    <div class="row-6 row__medium-4 row__large-3 row__xlarge-2 poster__item poster__item--no-hover"
                         data-description="{{ posterEvent.name }}">
                        <img class="lazyload blur-up"
                             decoding="async"
                             sizes="(max-width: 760px) 50vw, 25vw"
                             src="{{ asset(posterEvent.webPath(20)) }}"
                             data-srcset="
                            {% for dimension in posterEvent.wideDimensions %}
                                {% if not loop.last %}
                                    {{ asset(posterEvent.webPath(dimension)) }} {{ dimension }}w,
                                {% else %}
                                    {{ asset(posterEvent.webPath(dimension)) }} {{ dimension }}w
                                {% endif %}
                            {% endfor %}
                        "
                         alt=" {{ posterEvent.name }}">
                    </div>

                    {% for poster in posterEvent.posters %}
                        {% set alt = poster.author ~' '~ posterEvent.name %}
                        <div class="row-6 row__medium-4 row__large-3 row__xlarge-2 poster__item">
                            <div class="poster__item__overflow">
                                <a href="#"
                                   data-poster-big="{{ index }}"
                                   data-poster-max-width="{{ poster.getConstraintWideDimensions | last }}"
                                   data-poster-img="{{ asset(poster.getWebPath(null))}}"
                                   data-poster-img-details1-max-width="{{ poster.getConstraintWideDimensionsImageDetails1 | last }}"
                                   data-poster-img-detail1="{{ asset(poster.getWebPathImageDetail1(null))}}"
                                   data-poster-img-details2-max-width="{{ poster.getConstraintWideDimensionsImageDetails2 | last }}"
                                   data-poster-img-detail2="{{ asset(poster.getWebPathImageDetail2(null))}}"
                                   data-poster-title="{{ posterEvent.name }}"
                                   data-poster-author="{{ poster.author }}"
                                   data-poster-year="{{ poster.date == '' ? '' : poster.date  | date('Y') }}"
                                   data-poster-description="{{ poster.description | nl2br }}">

                                <img
                                    class="lazyload blur-up"
                                    decoding="async"
                                    sizes="(max-width: 530px) 50vw, (max-width: 800px) 33.33vw, 25vw"
                                    src="{{ asset(poster.webPath(20)) }}"
                                    data-srcset="
                                    {% for dimension in poster.getConstraintWideDimensions %}

                                        {% if not loop.last %}
                                            {{ asset(poster.webPath(dimension)) }} {{ dimension }}w,
                                        {% else %}
                                            {{ asset(poster.webPath(dimension)) }} {{ dimension }}w
                                        {% endif %}

                                    {% endfor %}
                                " alt="{{ alt }}">
                                </a>
                            </div>
                            <noscript>
                                <img src="{{ asset(poster.webPath()) }}" alt=" {{ alt }} ">
                            </noscript>

                            <p class=" poster__item__author">{{ poster.author }}</p>
                        </div>
                        {% set index = index+1 %}
                    {% endfor %}

                {% endfor %}
            </div>

            <div class="poster__search  row row--gutters">
            </div>

            {% if morePosterEvents %}
                <div id="posters__load__wrapper" class="load__animation__wrapper">
                    <div class="load__animation__wrapper__element"></div>
                </div>

                <div class="wrapper--center-text poster__button__wrapper">
                    <a href="#" id="loadMorePosters" class="btn btn--blue-inverse">Ver más</a>
                </div>
            {% endif %}

        </div>


    </div>
</section>

templates/modules/section__sites.html.twig
<section class="section" id="sites" data-nav-link-prev="#videos-link">
    <div class="wrapper wrapper--center-text">
        <h2 class="section__title">Sitios Sugeridos</h2>

        <div class="row row--gutters">
            {% for site in sites %}
                <div class="row__medium-4">
                    <a href="{{ site.url }}"
                       target="_blank"
                       rel="noopener">
                        <div class="logo">
                            <img class="lazyload blur-up"
                                 src="{{ asset(site.webPath(20)) }}"
                                 sizes="(max-width: 760px) 100vw, 33.33vw"
                                 data-src="{{ asset(site.webPath(500)) }}"
                                 alt="{{ site.name }}">
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</section>